---
title: Writing to get ideas
author: Ed
date: '2019-04-01'
slug: writing-to-get-ideas
categories: []
tags: []
---

Paul Graham writes about writing to generate ideas.

Put a link to that here.

Some ideas I have, or questions I am working on in my head:

When is it worth automating a process?

What percentage of jobs are answering emails about powerpoint slides, making power point slides, and then presenting powerpoint slides?

How do you move a process that is in excel into a process in python or R?

How do you motivate or change behavior? Can it only happen through competition/ threat?

For R specifically: Right now, how do you use R to build topics? 
                    How do you use it for sentiment analysis? 
                    How do you use topic generation and sentiment analysis to build models? 
                    What can you predict from topic generation and sentiment analysis about       podcasts from their transcripts?
                    Are there any tools out there for R to take a recodering and build ?
                    
The last question led to this:
https://www.r-bloggers.com/intro-to-sound-analysis-with-r/

https://www.pnas.org/content/early/2013/06/12/1221464110.abstract

could we do this for to tell deforestation?

another topic, reworking old projects, to either put them down a different path, or to add best practices that you have since learned, or to go deeper on one aspect. 
                    
                    